/*
 * SPDX-FileCopyrightText: Copyright (c) 2021 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#ifndef PARAMS_H_
#define PARAMS_H_

#define THREADS_FOR_VOXEL 256 // threads number for a block


// points2features
#define MAX_POINTS_NUM 50000
#define MAX_POINTS_NUM_1 30000 
#define MAX_PILLARS_NUM 10000
#define POINTS_NUM_PER_VOXEL 48//3558
#define VOXEL_SIZE_X 0.32
#define VOXEL_SIZE_Y 0.32
#define VOXEL_SIZE_Z 8.0
#define X_MIN -74.88
#define X_MAX 74.88
#define Y_MIN -74.88
#define Y_MAX 74.88
#define Z_MIN -5.0
#define Z_MAX 3.0
#define  GRID_SIZE_X 468
#define GRID_SIZE_Y 468 
#define GRID_SIZE_Z 1
#define POINT_FEATURE_NUM 4
#define FEATURES_NUM 10

#define PFN_LAYER_0_OUT_CHANNEL 96
#define PFN_LAYER_1_OUT_CHANNEL 192
#define ARRAY_LEN 200

//dsvt_input_layer
#define SPARSE_SHAPE_X 468
#define SPARSE_SHAPE_Y 468
#define SPARSE_SHAPE_Z 1

#define WIN_SHAPE_0_X 12
#define WIN_SHAPE_0_Y 12
#define WIN_SHAPE_0_Z 1

#define SHIFT_0_X 0
#define SHIFT_0_Y 0
#define SHIFT_0_Z 0

#define WIN_SHAPE_1_X 24
#define WIN_SHAPE_1_Y 24
#define WIN_SHAPE_1_Z 1

#define SHIFT_1_X 6
#define SHIFT_1_Y 6
#define SHIFT_1_Z 0

#define MAX_VOXEL_NUM_PER_WIN  576 // >24*24 and 12*12
#define MAX_WIN_NUM 800//     3200 40*40*2
#define  VOXEL_NUM_SET  36 

//dsvt
#define NUM_HEADS 8
#define EPS  0.00001
#define GELU_A  0.5   
#define GELU_B  0.7978845608028654   // sqrt(2.0/pi)
#define GELU_C 0.035677408136300125  // 0.044715 * sqrt(2.0/pi)

#define POSEMBED_LAYBERS_IN_FEATURES 2
#define POSEMBED_LAYBERS_OUT_FEATURES 192

#define SET_ATTENTION_0_0_OUT_CHANNEL_LINEAR_1  384
#define SET_ATTENTION_0_0_OUT_CHANNEL_LINEAR_2   192
#define  SET_ATTENTION_0_0_GELU_OUT_CHANNEL    384

//backbone  2d
//block0
//block0_0
#define BACKBONE_2D_BLOCK_0_0_1_IN_CHANNEL  192
#define BACKBONE_2D_BLOCK_0_0_1_OUT_CHANNEL 128
#define BACKBONE_2D_BLOCK_0_0_1_KERNEL_SIZE  3
#define BACKBONE_2D_BLOCK_0_0_1_STRIDE 1
#define BACKBONE_2D_BLOCK_0_0_1_PADDING  1

#define BACKBONE_2D_BLOCK_0_0_2_IN_CHANNEL  128
#define BACKBONE_2D_BLOCK_0_0_2_OUT_CHANNEL 128
#define BACKBONE_2D_BLOCK_0_0_2_KERNEL_SIZE  3
#define BACKBONE_2D_BLOCK_0_0_2_STRIDE 1
#define BACKBONE_2D_BLOCK_0_0_2_PADDING  1

#define BACKBONE_2D_BLOCK_0_0_DOWNSAMPLE_LAYER_IN_CHANNEL  192
#define BACKBONE_2D_BLOCK_0_0_DOWNSAMPLE_LAYER_OUT_CHANNEL 128
#define BACKBONE_2D_BLOCK_0_0_DOWNSAMPLE_LAYER_KERNEL_SIZE  1
#define BACKBONE_2D_BLOCK_0_0_DOWNSAMPLE_LAYER_STRIDE 1
#define BACKBONE_2D_BLOCK_0_0_DOWNSAMPLE_LAYER_PADDING  0

//block0_1
#define BACKBONE_2D_BLOCK_0_1_1_IN_CHANNEL  128
#define BACKBONE_2D_BLOCK_0_1_1_OUT_CHANNEL 128
#define BACKBONE_2D_BLOCK_0_1_1_KERNEL_SIZE  3
#define BACKBONE_2D_BLOCK_0_1_1_STRIDE 1
#define BACKBONE_2D_BLOCK_0_1_1_PADDING  1

#define BACKBONE_2D_BLOCK_0_1_2_IN_CHANNEL  128
#define BACKBONE_2D_BLOCK_0_1_2_OUT_CHANNEL 128
#define BACKBONE_2D_BLOCK_0_1_2_KERNEL_SIZE  3
#define BACKBONE_2D_BLOCK_0_1_2_STRIDE 1
#define BACKBONE_2D_BLOCK_0_1_2_PADDING  1

//block1
//block1_0
#define BACKBONE_2D_BLOCK_1_0_1_IN_CHANNEL  128
#define BACKBONE_2D_BLOCK_1_0_1_OUT_CHANNEL 128
#define BACKBONE_2D_BLOCK_1_0_1_KERNEL_SIZE  3
#define BACKBONE_2D_BLOCK_1_0_1_STRIDE 2
#define BACKBONE_2D_BLOCK_1_0_1_PADDING  1

#define BACKBONE_2D_BLOCK_1_0_2_IN_CHANNEL  128
#define BACKBONE_2D_BLOCK_1_0_2_OUT_CHANNEL 128
#define BACKBONE_2D_BLOCK_1_0_2_KERNEL_SIZE  3
#define BACKBONE_2D_BLOCK_1_0_2_STRIDE 1
#define BACKBONE_2D_BLOCK_1_0_2_PADDING  1

#define BACKBONE_2D_BLOCK_1_0_DOWNSAMPLE_LAYER_IN_CHANNEL  128
#define BACKBONE_2D_BLOCK_1_0_DOWNSAMPLE_LAYER_OUT_CHANNEL 128
#define BACKBONE_2D_BLOCK_1_0_DOWNSAMPLE_LAYER_KERNEL_SIZE  1
#define BACKBONE_2D_BLOCK_1_0_DOWNSAMPLE_LAYER_STRIDE 2
#define BACKBONE_2D_BLOCK_1_0_DOWNSAMPLE_LAYER_PADDING  0

//block1_1
#define BACKBONE_2D_BLOCK_1_1_1_IN_CHANNEL  128
#define BACKBONE_2D_BLOCK_1_1_1_OUT_CHANNEL 128
#define BACKBONE_2D_BLOCK_1_1_1_KERNEL_SIZE  3
#define BACKBONE_2D_BLOCK_1_1_1_STRIDE 1
#define BACKBONE_2D_BLOCK_1_1_1_PADDING  1

#define BACKBONE_2D_BLOCK_1_1_2_IN_CHANNEL  128
#define BACKBONE_2D_BLOCK_1_1_2_OUT_CHANNEL 128
#define BACKBONE_2D_BLOCK_1_1_2_KERNEL_SIZE  3
#define BACKBONE_2D_BLOCK_1_1_2_STRIDE 1
#define BACKBONE_2D_BLOCK_1_1_2_PADDING  1

//block1_2
#define BACKBONE_2D_BLOCK_1_2_1_IN_CHANNEL  128
#define BACKBONE_2D_BLOCK_1_2_1_OUT_CHANNEL 128
#define BACKBONE_2D_BLOCK_1_2_1_KERNEL_SIZE  3
#define BACKBONE_2D_BLOCK_1_2_1_STRIDE 1
#define BACKBONE_2D_BLOCK_1_2_1_PADDING  1

#define BACKBONE_2D_BLOCK_1_2_2_IN_CHANNEL  128
#define BACKBONE_2D_BLOCK_1_2_2_OUT_CHANNEL 128
#define BACKBONE_2D_BLOCK_1_2_2_KERNEL_SIZE  3
#define BACKBONE_2D_BLOCK_1_2_2_STRIDE 1
#define BACKBONE_2D_BLOCK_1_2_2_PADDING  1


//block2
//block2_0
#define BACKBONE_2D_BLOCK_2_0_1_IN_CHANNEL  128
#define BACKBONE_2D_BLOCK_2_0_1_OUT_CHANNEL 256
#define BACKBONE_2D_BLOCK_2_0_1_KERNEL_SIZE  3
#define BACKBONE_2D_BLOCK_2_0_1_STRIDE 2
#define BACKBONE_2D_BLOCK_2_0_1_PADDING  1

#define BACKBONE_2D_BLOCK_2_0_2_IN_CHANNEL  256
#define BACKBONE_2D_BLOCK_2_0_2_OUT_CHANNEL 256
#define BACKBONE_2D_BLOCK_2_0_2_KERNEL_SIZE  3
#define BACKBONE_2D_BLOCK_2_0_2_STRIDE 1
#define BACKBONE_2D_BLOCK_2_0_2_PADDING  1

#define BACKBONE_2D_BLOCK_2_0_DOWNSAMPLE_LAYER_IN_CHANNEL  128
#define BACKBONE_2D_BLOCK_2_0_DOWNSAMPLE_LAYER_OUT_CHANNEL 256
#define BACKBONE_2D_BLOCK_2_0_DOWNSAMPLE_LAYER_KERNEL_SIZE  1
#define BACKBONE_2D_BLOCK_2_0_DOWNSAMPLE_LAYER_STRIDE 2
#define BACKBONE_2D_BLOCK_2_0_DOWNSAMPLE_LAYER_PADDING  0

//block2_1
#define BACKBONE_2D_BLOCK_2_1_1_IN_CHANNEL  256
#define BACKBONE_2D_BLOCK_2_1_1_OUT_CHANNEL 256
#define BACKBONE_2D_BLOCK_2_1_1_KERNEL_SIZE  3
#define BACKBONE_2D_BLOCK_2_1_1_STRIDE 1
#define BACKBONE_2D_BLOCK_2_1_1_PADDING  1

#define BACKBONE_2D_BLOCK_2_1_2_IN_CHANNEL  256
#define BACKBONE_2D_BLOCK_2_1_2_OUT_CHANNEL 256
#define BACKBONE_2D_BLOCK_2_1_2_KERNEL_SIZE  3
#define BACKBONE_2D_BLOCK_2_1_2_STRIDE 1
#define BACKBONE_2D_BLOCK_2_1_2_PADDING  1

//block2_2
#define BACKBONE_2D_BLOCK_2_2_1_IN_CHANNEL  256
#define BACKBONE_2D_BLOCK_2_2_1_OUT_CHANNEL 256
#define BACKBONE_2D_BLOCK_2_2_1_KERNEL_SIZE  3
#define BACKBONE_2D_BLOCK_2_2_1_STRIDE 1
#define BACKBONE_2D_BLOCK_2_2_1_PADDING  1

#define BACKBONE_2D_BLOCK_2_2_2_IN_CHANNEL  256
#define BACKBONE_2D_BLOCK_2_2_2_OUT_CHANNEL 256
#define BACKBONE_2D_BLOCK_2_2_2_KERNEL_SIZE  3
#define BACKBONE_2D_BLOCK_2_2_2_STRIDE 1
#define BACKBONE_2D_BLOCK_2_2_2_PADDING  1

//deblock0
#define BACKBONE_2D_BLOCK_0_DECONV_IN_CHANNEL  128
#define BACKBONE_2D_BLOCK_0_DECONV_OUT_CHANNEL 128
#define BACKBONE_2D_BLOCK_0_DECONV_KERNEL_SIZE  1
#define BACKBONE_2D_BLOCK_0_DECONV_STRIDE 1
#define BACKBONE_2D_BLOCK_0_DECONV_PADDING  0


//deblock1
#define BACKBONE_2D_BLOCK_1_DECONV_IN_CHANNEL  128
#define BACKBONE_2D_BLOCK_1_DECONV_OUT_CHANNEL 128
#define BACKBONE_2D_BLOCK_1_DECONV_KERNEL_SIZE  2
#define BACKBONE_2D_BLOCK_1_DECONV_STRIDE 2
#define BACKBONE_2D_BLOCK_1_DECONV_PADDING  0

//deblock2
#define BACKBONE_2D_BLOCK_2_DECONV_IN_CHANNEL  256
#define BACKBONE_2D_BLOCK_2_DECONV_OUT_CHANNEL 128
#define BACKBONE_2D_BLOCK_2_DECONV_KERNEL_SIZE  4
#define BACKBONE_2D_BLOCK_2_DECONV_STRIDE 4
#define BACKBONE_2D_BLOCK_2_DECONV_PADDING  0



////// center_head
#define CENTER_HEAD_SHARED_CONV_IN_CHANNEL 384
#define CENTER_HEAD_SHARED_CONV_OUT_CHANNEL 64
#define CENTER_HEAD_SHARED_CONV_KERNEL_SIZE 3
#define CENTER_HEAD_SHARED_CONV_STRIDE 1
#define CENTER_HEAD_SHARED_CONV_PADDING 1


//center
#define CENTER_SEQ_0_CONV_0_IN_CHANNEL 64
#define CENTER_SEQ_0_CONV_0_OUT_CHANNEL 64
#define CENTER_SEQ_0_CONV_0_KERNEL_SIZE 3
#define CENTER_SEQ_0_CONV_0_STRIDE 1
#define CENTER_SEQ_0_CONV_0_IN_PADDING 1

#define CENTER_CONV_1_IN_CHANNEL 64
#define CENTER_CONV_1_OUT_CHANNEL 2
#define CENTER_CONV_1_KERNEL_SIZE 3
#define CENTER_CONV_1_STRIDE 1
#define CENTER_CONV_1_IN_PADDING 1


//center_z
#define CENTER_Z_SEQ_0_CONV_0_IN_CHANNEL 64
#define CENTER_Z_SEQ_0_CONV_0_OUT_CHANNEL 64
#define CENTER_Z_SEQ_0_CONV_0_KERNEL_SIZE 3
#define CENTER_Z_SEQ_0_CONV_0_STRIDE 1
#define CENTER_Z_SEQ_0_CONV_0_IN_PADDING 1

#define CENTER_Z_CONV_1_IN_CHANNEL 64
#define CENTER_Z_CONV_1_OUT_CHANNEL 1
#define CENTER_Z_CONV_1_KERNEL_SIZE 3
#define CENTER_Z_CONV_1_STRIDE 1
#define CENTER_Z_CONV_1_IN_PADDING 1

//dim 
#define DIM_SEQ_0_CONV_0_IN_CHANNEL 64
#define DIM_SEQ_0_CONV_0_OUT_CHANNEL 64
#define DIM_SEQ_0_CONV_0_KERNEL_SIZE 3
#define DIM_SEQ_0_CONV_0_STRIDE 1
#define DIM_SEQ_0_CONV_0_IN_PADDING 1

#define DIM_CONV_1_IN_CHANNEL 64
#define DIM_CONV_1_OUT_CHANNEL 3
#define DIM_CONV_1_KERNEL_SIZE 3
#define DIM_CONV_1_STRIDE 1
#define DIM_CONV_1_IN_PADDING 1

//rot
#define ROT_SEQ_0_CONV_0_IN_CHANNEL 64
#define ROT_SEQ_0_CONV_0_OUT_CHANNEL 64
#define ROT_SEQ_0_CONV_0_KERNEL_SIZE 3
#define ROT_SEQ_0_CONV_0_STRIDE 1
#define ROT_SEQ_0_CONV_0_IN_PADDING 1

#define ROT_CONV_1_IN_CHANNEL 64
#define ROT_CONV_1_OUT_CHANNEL 2
#define ROT_CONV_1_KERNEL_SIZE 3
#define ROT_CONV_1_STRIDE 1
#define ROT_CONV_1_IN_PADDING 1

//iou
#define IOU_SEQ_0_CONV_0_IN_CHANNEL 64
#define IOU_SEQ_0_CONV_0_OUT_CHANNEL 64
#define IOU_SEQ_0_CONV_0_KERNEL_SIZE 3
#define IOU_SEQ_0_CONV_0_STRIDE 1
#define IOU_SEQ_0_CONV_0_IN_PADDING 1

#define IOU_CONV_1_IN_CHANNEL 64
#define IOU_CONV_1_OUT_CHANNEL 1
#define IOU_CONV_1_KERNEL_SIZE 3
#define IOU_CONV_1_STRIDE 1
#define IOU_CONV_1_IN_PADDING 1

//hm
#define HM_SEQ_0_CONV_0_IN_CHANNEL 64
#define HM_SEQ_0_CONV_0_OUT_CHANNEL 64
#define HM_SEQ_0_CONV_0_KERNEL_SIZE 3
#define HM_SEQ_0_CONV_0_STRIDE 1
#define HM_SEQ_0_CONV_0_IN_PADDING 1

#define HM_CONV_1_IN_CHANNEL 64
#define HM_CONV_1_OUT_CHANNEL 10
#define HM_CONV_1_KERNEL_SIZE 3
#define HM_CONV_1_STRIDE 1
#define HM_CONV_1_IN_PADDING 1



//postprocessing
#define HM_TOP_K 500
#define SCORE_THRESHOLD 0.3 //0.3



// #define USE_FP16// comment out this if want to use FP32
#define DEVICE 0  // GPU id
#define NMS_THRESH 0.01
#define LAST_DIMS 9

#endif
